// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protodoc.proto

package protodoc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConvertReq struct {
	// proto3 定义的协议内容
	Proto string `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	// 协议文件名，用于解析时的附加信息
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertReq) Reset()         { *m = ConvertReq{} }
func (m *ConvertReq) String() string { return proto.CompactTextString(m) }
func (*ConvertReq) ProtoMessage()    {}
func (*ConvertReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_253dd10202917d43, []int{0}
}

func (m *ConvertReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertReq.Unmarshal(m, b)
}
func (m *ConvertReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertReq.Marshal(b, m, deterministic)
}
func (m *ConvertReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertReq.Merge(m, src)
}
func (m *ConvertReq) XXX_Size() int {
	return xxx_messageInfo_ConvertReq.Size(m)
}
func (m *ConvertReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertReq proto.InternalMessageInfo

func (m *ConvertReq) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *ConvertReq) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type ConvertRes struct {
	// HTML 格式的文档
	Html                 string   `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertRes) Reset()         { *m = ConvertRes{} }
func (m *ConvertRes) String() string { return proto.CompactTextString(m) }
func (*ConvertRes) ProtoMessage()    {}
func (*ConvertRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_253dd10202917d43, []int{1}
}

func (m *ConvertRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertRes.Unmarshal(m, b)
}
func (m *ConvertRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertRes.Marshal(b, m, deterministic)
}
func (m *ConvertRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertRes.Merge(m, src)
}
func (m *ConvertRes) XXX_Size() int {
	return xxx_messageInfo_ConvertRes.Size(m)
}
func (m *ConvertRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertRes.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertRes proto.InternalMessageInfo

func (m *ConvertRes) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

func init() {
	proto.RegisterType((*ConvertReq)(nil), "protodoc.ConvertReq")
	proto.RegisterType((*ConvertRes)(nil), "protodoc.ConvertRes")
}

func init() {
	proto.RegisterFile("protodoc.proto", fileDescriptor_253dd10202917d43)
}

var fileDescriptor_253dd10202917d43 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xc9, 0x4f, 0xd6, 0x03, 0x33, 0x84, 0x38, 0x60, 0x7c, 0x25, 0x3b, 0x2e, 0x2e, 0xe7,
	0xfc, 0xbc, 0xb2, 0xd4, 0xa2, 0x92, 0xa0, 0xd4, 0x42, 0x21, 0x11, 0x2e, 0x56, 0xb0, 0x8c, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0x23, 0x24, 0xc5, 0xc5, 0x91, 0x96, 0x99, 0x93, 0x9a,
	0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x04, 0x96, 0x80, 0xf3, 0x95, 0x14, 0x90, 0xf4, 0x17, 0x0b, 0x09,
	0x71, 0xb1, 0x64, 0x94, 0xe4, 0xe6, 0x40, 0x55, 0x81, 0xd9, 0x46, 0x8e, 0x5c, 0x1c, 0x01, 0x20,
	0x63, 0x5c, 0xf2, 0x93, 0x85, 0x4c, 0xb9, 0xd8, 0xa1, 0xaa, 0x85, 0x44, 0xf4, 0xe0, 0x6e, 0x42,
	0x38, 0x40, 0x0a, 0x9b, 0x68, 0x71, 0x12, 0x1b, 0x58, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x42, 0xb1, 0x50, 0x49, 0xc7, 0x00, 0x00, 0x00,
}
