// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protodoc.proto

package protodoc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConvertReq struct {
	// proto3 定义的协议内容
	Proto string `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	// 协议文件名，用于解析时的附加信息
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertReq) Reset()         { *m = ConvertReq{} }
func (m *ConvertReq) String() string { return proto.CompactTextString(m) }
func (*ConvertReq) ProtoMessage()    {}
func (*ConvertReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_253dd10202917d43, []int{0}
}

func (m *ConvertReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertReq.Unmarshal(m, b)
}
func (m *ConvertReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertReq.Marshal(b, m, deterministic)
}
func (m *ConvertReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertReq.Merge(m, src)
}
func (m *ConvertReq) XXX_Size() int {
	return xxx_messageInfo_ConvertReq.Size(m)
}
func (m *ConvertReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertReq proto.InternalMessageInfo

func (m *ConvertReq) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *ConvertReq) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type ConvertRes struct {
	// HTML 格式的文档
	Html                 string   `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertRes) Reset()         { *m = ConvertRes{} }
func (m *ConvertRes) String() string { return proto.CompactTextString(m) }
func (*ConvertRes) ProtoMessage()    {}
func (*ConvertRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_253dd10202917d43, []int{1}
}

func (m *ConvertRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertRes.Unmarshal(m, b)
}
func (m *ConvertRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertRes.Marshal(b, m, deterministic)
}
func (m *ConvertRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertRes.Merge(m, src)
}
func (m *ConvertRes) XXX_Size() int {
	return xxx_messageInfo_ConvertRes.Size(m)
}
func (m *ConvertRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertRes.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertRes proto.InternalMessageInfo

func (m *ConvertRes) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

type HelloReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReq) Reset()         { *m = HelloReq{} }
func (m *HelloReq) String() string { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()    {}
func (*HelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_253dd10202917d43, []int{2}
}

func (m *HelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReq.Unmarshal(m, b)
}
func (m *HelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReq.Marshal(b, m, deterministic)
}
func (m *HelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReq.Merge(m, src)
}
func (m *HelloReq) XXX_Size() int {
	return xxx_messageInfo_HelloReq.Size(m)
}
func (m *HelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReq proto.InternalMessageInfo

type HelloRes struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRes) Reset()         { *m = HelloRes{} }
func (m *HelloRes) String() string { return proto.CompactTextString(m) }
func (*HelloRes) ProtoMessage()    {}
func (*HelloRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_253dd10202917d43, []int{3}
}

func (m *HelloRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRes.Unmarshal(m, b)
}
func (m *HelloRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRes.Marshal(b, m, deterministic)
}
func (m *HelloRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRes.Merge(m, src)
}
func (m *HelloRes) XXX_Size() int {
	return xxx_messageInfo_HelloRes.Size(m)
}
func (m *HelloRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRes.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRes proto.InternalMessageInfo

func (m *HelloRes) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*ConvertReq)(nil), "protodoc.ConvertReq")
	proto.RegisterType((*ConvertRes)(nil), "protodoc.ConvertRes")
	proto.RegisterType((*HelloReq)(nil), "protodoc.HelloReq")
	proto.RegisterType((*HelloRes)(nil), "protodoc.HelloRes")
}

func init() {
	proto.RegisterFile("protodoc.proto", fileDescriptor_253dd10202917d43)
}

var fileDescriptor_253dd10202917d43 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xc9, 0x4f, 0xd6, 0x03, 0x33, 0x84, 0x38, 0x60, 0x7c, 0x25, 0x3b, 0x2e, 0x2e, 0xe7,
	0xfc, 0xbc, 0xb2, 0xd4, 0xa2, 0x92, 0xa0, 0xd4, 0x42, 0x21, 0x11, 0x2e, 0x56, 0xb0, 0x8c, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0x23, 0x24, 0xc5, 0xc5, 0x91, 0x96, 0x99, 0x93, 0x9a,
	0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x04, 0x96, 0x80, 0xf3, 0x95, 0x14, 0x90, 0xf4, 0x17, 0x0b, 0x09,
	0x71, 0xb1, 0x64, 0x94, 0xe4, 0xe6, 0x40, 0x55, 0x81, 0xd9, 0x4a, 0x5c, 0x5c, 0x1c, 0x1e, 0xa9,
	0x39, 0x39, 0xf9, 0x41, 0xa9, 0x85, 0x4a, 0x72, 0x70, 0x36, 0x58, 0x6d, 0x4a, 0x62, 0x49, 0x22,
	0xd4, 0x2a, 0x30, 0xdb, 0xc8, 0x91, 0x8b, 0x23, 0x00, 0x64, 0xa5, 0x4b, 0x7e, 0xb2, 0x90, 0x29,
	0x17, 0x3b, 0xd4, 0x64, 0x21, 0x11, 0x3d, 0xb8, 0xfb, 0x11, 0x8e, 0x95, 0xc2, 0x26, 0x5a, 0x6c,
	0x64, 0xc1, 0xc5, 0x0a, 0xb6, 0x42, 0x48, 0x1f, 0xc6, 0x10, 0x42, 0xa8, 0x83, 0x39, 0x44, 0x0a,
	0x53, 0xac, 0x38, 0x89, 0x0d, 0x2c, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x70, 0xe7, 0xce,
	0x37, 0x2d, 0x01, 0x00, 0x00,
}
